<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Memorial;
use App\Models\Tribute;
use App\Models\User;
use App\Models\VirtualGift;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CelebritySeeder extends Seeder
{
    public function run(): void
    {
        $user = User::firstOrCreate(
            ['email' => 'test@example.com'],
            ['name' => 'Test User', 'password' => bcrypt('password')],
        );

        $celebrities = $this->getCelebrities();

        $tributeMessages = $this->getTributeMessages();
        $tributeAuthors = [
            'Sarah M.', 'James W.', 'Emily R.', 'Michael C.', 'Lisa T.',
            'David K.', 'Jennifer P.', 'Robert H.', 'Amanda S.', 'Chris B.',
            'Maria L.', 'Thomas F.', 'Rachel G.', 'Daniel N.', 'Laura V.',
            'Kevin D.', 'Sophia A.', 'Brian J.', 'Nicole E.', 'Andrew Z.',
        ];

        $giftTypes = ['candle', 'flower', 'tree', 'wreath', 'star'];
        $giftMessages = [
            'Rest in peace', 'Forever in our hearts', 'Gone but never forgotten',
            'Your legacy lives on', 'Thank you for everything', 'We miss you',
            'A light in the darkness', 'Eternal memory', null, null,
        ];

        foreach ($celebrities as $celeb) {
            $memorial = Memorial::create([
                'user_id' => $user->id,
                'slug' => Str::slug($celeb['first_name'] . ' ' . $celeb['last_name']),
                'first_name' => $celeb['first_name'],
                'last_name' => $celeb['last_name'],
                'maiden_name' => $celeb['maiden_name'] ?? null,
                'date_of_birth' => $celeb['born'],
                'date_of_death' => $celeb['died'],
                'place_of_birth' => $celeb['birth_place'],
                'place_of_death' => $celeb['death_place'],
                'obituary' => $celeb['obituary'],
                'privacy' => 'public',
                'is_published' => true,
                'cemetery_name' => $celeb['cemetery'] ?? null,
                'cemetery_address' => $celeb['cemetery_address'] ?? null,
            ]);

            $tributeCount = random_int(1, 5);
            $usedMessages = array_rand(array_flip($tributeMessages), min($tributeCount, count($tributeMessages)));
            if (!is_array($usedMessages)) {
                $usedMessages = [$usedMessages];
            }

            foreach ($usedMessages as $msg) {
                Tribute::create([
                    'memorial_id' => $memorial->id,
                    'author_name' => $tributeAuthors[array_rand($tributeAuthors)],
                    'body' => $msg,
                    'is_approved' => true,
                ]);
            }

            $giftCount = random_int(2, 10);
            for ($i = 0; $i < $giftCount; $i++) {
                VirtualGift::create([
                    'memorial_id' => $memorial->id,
                    'type' => $giftTypes[array_rand($giftTypes)],
                    'message' => $giftMessages[array_rand($giftMessages)],
                ]);
            }
        }
    }

    /**
     * @return list<array{first_name: string, last_name: string, born: string, died: string, birth_place: string, death_place: string, obituary: string, cemetery?: string, cemetery_address?: string, maiden_name?: string}>
     */
    private function getCelebrities(): array
    {
        return [
            [
                'first_name' => 'Freddie',
                'last_name' => 'Mercury',
                'born' => '1946-09-05',
                'died' => '1991-11-24',
                'birth_place' => 'Stone Town, Zanzibar',
                'death_place' => 'Kensington, London, England',
                'obituary' => 'Freddie Mercury, born Farrokh Bulsara, was the legendary lead vocalist and songwriter of the rock band Queen. Known for his extraordinary vocal range, flamboyant stage presence, and genre-defying music, Mercury crafted anthems like "Bohemian Rhapsody," "We Are the Champions," and "Somebody to Love." His four-octave vocal range and theatrical performances redefined what rock music could be. Mercury\'s artistry transcended boundaries of genre, culture, and convention, making him one of the most iconic performers in the history of popular music.',
                'cemetery' => 'Kensal Green Cemetery',
                'cemetery_address' => 'Harrow Rd, London W10 4RA, United Kingdom',
            ],
            [
                'first_name' => 'Princess',
                'last_name' => 'Diana',
                'maiden_name' => 'Spencer',
                'born' => '1961-07-01',
                'died' => '1997-08-31',
                'birth_place' => 'Sandringham, Norfolk, England',
                'death_place' => 'Paris, France',
                'obituary' => 'Diana, Princess of Wales, was a member of the British royal family and an international humanitarian icon. Her warmth, compassion, and dedication to charitable causes — particularly landmine removal, AIDS awareness, and children\'s welfare — earned her the title "The People\'s Princess." Diana\'s grace, authenticity, and willingness to challenge royal convention made her one of the most beloved public figures of the 20th century.',
                'cemetery' => 'Althorp Estate',
                'cemetery_address' => 'Althorp, Northampton NN7 4HG, United Kingdom',
            ],
            [
                'first_name' => 'Albert',
                'last_name' => 'Einstein',
                'born' => '1879-03-14',
                'died' => '1955-04-18',
                'birth_place' => 'Ulm, Kingdom of Württemberg, German Empire',
                'death_place' => 'Princeton, New Jersey, USA',
                'obituary' => 'Albert Einstein was a theoretical physicist widely regarded as one of the greatest minds in human history. His theory of relativity revolutionized the understanding of space, time, and energy. Awarded the Nobel Prize in Physics in 1921 for his explanation of the photoelectric effect, Einstein\'s contributions to science fundamentally reshaped modern physics. Beyond his scientific genius, he was a passionate advocate for peace, civil rights, and intellectual freedom.',
            ],
            [
                'first_name' => 'Marilyn',
                'last_name' => 'Monroe',
                'maiden_name' => 'Mortenson',
                'born' => '1926-06-01',
                'died' => '1962-08-04',
                'birth_place' => 'Los Angeles, California, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Marilyn Monroe, born Norma Jeane Mortenson, was an American actress, model, and singer who became one of the most iconic figures of the 20th century. Her luminous screen presence in films like "Some Like It Hot," "Gentlemen Prefer Blondes," and "The Seven Year Itch" captivated audiences worldwide. Beyond her blonde bombshell image, Monroe was a talented comedic actress and a complex, intelligent woman whose life and legacy continue to fascinate generations.',
                'cemetery' => 'Westwood Village Memorial Park',
                'cemetery_address' => '1218 Glendon Ave, Los Angeles, CA 90024, USA',
            ],
            [
                'first_name' => 'Martin Luther',
                'last_name' => 'King Jr.',
                'born' => '1929-01-15',
                'died' => '1968-04-04',
                'birth_place' => 'Atlanta, Georgia, USA',
                'death_place' => 'Memphis, Tennessee, USA',
                'obituary' => 'Dr. Martin Luther King Jr. was an American Baptist minister and activist who became the most visible leader of the civil rights movement from 1955 until his assassination in 1968. His philosophy of nonviolent resistance, inspired by Mahatma Gandhi, led to landmark legislation including the Civil Rights Act of 1964 and the Voting Rights Act of 1965. His "I Have a Dream" speech remains one of the most powerful orations in American history. He was awarded the Nobel Peace Prize in 1964.',
                'cemetery' => 'Martin Luther King Jr. National Historical Park',
                'cemetery_address' => '450 Auburn Ave NE, Atlanta, GA 30312, USA',
            ],
            [
                'first_name' => 'John',
                'last_name' => 'Lennon',
                'born' => '1940-10-09',
                'died' => '1980-12-08',
                'birth_place' => 'Liverpool, England',
                'death_place' => 'New York City, New York, USA',
                'obituary' => 'John Lennon was an English singer, songwriter, and peace activist who co-founded the Beatles, the most commercially successful band in the history of popular music. As a songwriter in partnership with Paul McCartney, he wrote some of the most beloved songs of the 20th century. After the Beatles disbanded, Lennon pursued a solo career producing timeless works like "Imagine." His advocacy for peace and his artistic vision continue to inspire millions worldwide.',
            ],
            [
                'first_name' => 'Audrey',
                'last_name' => 'Hepburn',
                'born' => '1929-05-04',
                'died' => '1993-01-20',
                'birth_place' => 'Brussels, Belgium',
                'death_place' => 'Tolochenaz, Switzerland',
                'obituary' => 'Audrey Hepburn was a British actress and humanitarian regarded as one of the greatest screen legends of Hollywood\'s Golden Age. Her roles in "Roman Holiday," "Breakfast at Tiffany\'s," and "My Fair Lady" showcased her elegance, charm, and remarkable talent. Later in life, she devoted herself to UNICEF, traveling to some of the world\'s most impoverished regions. Hepburn remains an enduring symbol of grace, beauty, and compassion.',
                'cemetery' => 'Tolochenaz Cemetery',
                'cemetery_address' => 'Tolochenaz, Switzerland',
            ],
            [
                'first_name' => 'Leonardo',
                'last_name' => 'da Vinci',
                'born' => '1452-04-15',
                'died' => '1519-05-02',
                'birth_place' => 'Vinci, Republic of Florence',
                'death_place' => 'Amboise, Kingdom of France',
                'obituary' => 'Leonardo da Vinci was an Italian polymath of the Renaissance whose genius spanned art, science, engineering, anatomy, and architecture. Creator of masterpieces including the "Mona Lisa" and "The Last Supper," he is widely considered one of the greatest painters of all time. His notebooks reveal a mind centuries ahead of its time, filled with designs for flying machines, anatomical studies, and engineering marvels. Leonardo embodies the ideal of the universal genius.',
                'cemetery' => 'Chapel of Saint-Hubert',
                'cemetery_address' => 'Château d\'Amboise, 37400 Amboise, France',
            ],
            [
                'first_name' => 'Nikola',
                'last_name' => 'Tesla',
                'born' => '1856-07-10',
                'died' => '1943-01-07',
                'birth_place' => 'Smiljan, Austrian Empire',
                'death_place' => 'New York City, New York, USA',
                'obituary' => 'Nikola Tesla was a Serbian-American inventor, electrical engineer, and futurist best known for his contributions to the design of the modern alternating current electricity supply system. His inventions and theoretical work formed the basis of modern AC electrical power and contributed to the development of radio, robotics, and wireless communication. A visionary far ahead of his time, Tesla\'s legacy has only grown in the decades since his death.',
                'cemetery' => 'Nikola Tesla Museum',
                'cemetery_address' => 'Krunska 51, Belgrade, Serbia',
            ],
            [
                'first_name' => 'Frida',
                'last_name' => 'Kahlo',
                'born' => '1907-07-06',
                'died' => '1954-07-13',
                'birth_place' => 'Coyoacán, Mexico City, Mexico',
                'death_place' => 'Coyoacán, Mexico City, Mexico',
                'obituary' => 'Frida Kahlo was a Mexican painter known for her vivid, deeply personal self-portraits that explored identity, post-colonialism, gender, class, and race. Her work, influenced by Mexican folk art, surrealism, and her own turbulent life experiences including chronic pain from a near-fatal bus accident, has made her an icon of resilience and artistic authenticity. Kahlo\'s art and life story continue to inspire movements for feminism, LGBTQ+ rights, and Mexican cultural pride.',
                'cemetery' => 'Museo Frida Kahlo (La Casa Azul)',
                'cemetery_address' => 'Londres 247, Del Carmen, Coyoacán, 04100 Mexico City, Mexico',
            ],
            [
                'first_name' => 'Elvis',
                'last_name' => 'Presley',
                'born' => '1935-01-08',
                'died' => '1977-08-16',
                'birth_place' => 'Tupelo, Mississippi, USA',
                'death_place' => 'Memphis, Tennessee, USA',
                'obituary' => 'Elvis Aaron Presley was an American singer, musician, and actor, widely known as the "King of Rock and Roll." His energized interpretations of songs and sexually provocative performance style, combined with a singularly potent mix of influences across color lines during a transformative era in race relations, led him to great success and controversy. Presley is the best-selling solo music artist of all time, with estimated record sales of over 500 million units worldwide.',
                'cemetery' => 'Graceland',
                'cemetery_address' => '3764 Elvis Presley Blvd, Memphis, TN 38116, USA',
            ],
            [
                'first_name' => 'Marie',
                'last_name' => 'Curie',
                'maiden_name' => 'Skłodowska',
                'born' => '1867-11-07',
                'died' => '1934-07-04',
                'birth_place' => 'Warsaw, Congress Poland, Russian Empire',
                'death_place' => 'Passy, Haute-Savoie, France',
                'obituary' => 'Marie Curie was a Polish and naturalized-French physicist and chemist who conducted pioneering research on radioactivity. She was the first woman to win a Nobel Prize, the first person to win Nobel Prizes in two different sciences (Physics in 1903, Chemistry in 1911), and the first woman professor at the University of Paris. Her discoveries of polonium and radium advanced our understanding of atomic physics and opened new frontiers in medicine and science.',
                'cemetery' => 'Panthéon',
                'cemetery_address' => 'Place du Panthéon, 75005 Paris, France',
            ],
            [
                'first_name' => 'Bob',
                'last_name' => 'Marley',
                'born' => '1945-02-06',
                'died' => '1981-05-11',
                'birth_place' => 'Nine Mile, Saint Ann Parish, Jamaica',
                'death_place' => 'Miami, Florida, USA',
                'obituary' => 'Robert Nesta Marley was a Jamaican singer, songwriter, and musician who became an international icon through his music, which blended reggae, ska, and rocksteady. Marley\'s songs of love, social justice, and Rastafarian spirituality — including "No Woman, No Cry," "One Love," and "Redemption Song" — transcended cultural and national boundaries. He remains the most widely known and revered reggae performer and is credited with bringing Jamaican music to a worldwide audience.',
                'cemetery' => 'Bob Marley Mausoleum',
                'cemetery_address' => 'Nine Mile, Saint Ann Parish, Jamaica',
            ],
            [
                'first_name' => 'Steve',
                'last_name' => 'Jobs',
                'born' => '1955-02-24',
                'died' => '2011-10-05',
                'birth_place' => 'San Francisco, California, USA',
                'death_place' => 'Palo Alto, California, USA',
                'obituary' => 'Steve Jobs was an American business magnate, inventor, and co-founder of Apple Inc. His vision and relentless pursuit of perfection led to revolutionary products including the Macintosh, iPod, iPhone, and iPad that transformed personal computing, music, phones, and tablet computing. Jobs\'s emphasis on design, user experience, and innovation made Apple the world\'s most valuable company. His famous Stanford commencement speech remains a timeless call to "Stay Hungry, Stay Foolish."',
                'cemetery' => 'Alta Mesa Memorial Park',
                'cemetery_address' => '695 Arastradero Rd, Palo Alto, CA 94306, USA',
            ],
            [
                'first_name' => 'Whitney',
                'last_name' => 'Houston',
                'born' => '1963-08-09',
                'died' => '2012-02-11',
                'birth_place' => 'Newark, New Jersey, USA',
                'death_place' => 'Beverly Hills, California, USA',
                'obituary' => 'Whitney Houston was an American singer and actress who was one of the best-selling music artists of all time. Dubbed "The Voice," her powerful vocal ability and emotional delivery produced iconic hits including "I Will Always Love You," "Greatest Love of All," and "I Wanna Dance with Somebody." Houston\'s influence on pop, R&B, and gospel music is immeasurable, and she remains one of the most awarded female artists in history with over 200 million records sold worldwide.',
                'cemetery' => 'Fairview Cemetery',
                'cemetery_address' => '820 Westfield Ave, Westfield, NJ 07090, USA',
            ],
            [
                'first_name' => 'Muhammad',
                'last_name' => 'Ali',
                'born' => '1942-01-17',
                'died' => '2016-06-03',
                'birth_place' => 'Louisville, Kentucky, USA',
                'death_place' => 'Scottsdale, Arizona, USA',
                'obituary' => 'Muhammad Ali, born Cassius Marcellus Clay Jr., was an American professional boxer, activist, and philanthropist. Widely regarded as the greatest heavyweight boxer of all time, Ali was known for his unorthodox fighting style, quick footwork, and the iconic phrase "Float like a butterfly, sting like a bee." Beyond the ring, he was a champion of civil rights, religious freedom, and social justice. His charisma, wit, and courage in and out of the ring made him one of the 20th century\'s most significant and celebrated figures.',
                'cemetery' => 'Cave Hill Cemetery',
                'cemetery_address' => '701 Baxter Ave, Louisville, KY 40204, USA',
            ],
            [
                'first_name' => 'Amy',
                'last_name' => 'Winehouse',
                'born' => '1983-09-14',
                'died' => '2011-07-23',
                'birth_place' => 'Southgate, London, England',
                'death_place' => 'Camden, London, England',
                'obituary' => 'Amy Winehouse was a British singer and songwriter known for her deep, expressive contralto vocals and her eclectic mix of musical genres including soul, jazz, and R&B. Her critically acclaimed album "Back to Black" became one of the best-selling albums in UK history and won five Grammy Awards. Winehouse\'s raw honesty in her songwriting and her extraordinary vocal talent left an indelible mark on contemporary music despite her tragically short life.',
                'cemetery' => 'Edgwarebury Cemetery',
                'cemetery_address' => 'Edgwarebury Ln, Edgware HA8 8QP, United Kingdom',
            ],
            [
                'first_name' => 'Robin',
                'last_name' => 'Williams',
                'born' => '1951-07-21',
                'died' => '2014-08-11',
                'birth_place' => 'Chicago, Illinois, USA',
                'death_place' => 'Paradise Cay, California, USA',
                'obituary' => 'Robin Williams was an American actor and comedian widely regarded as one of the greatest entertainers of all time. From his breakout role in "Mork & Mindy" to Oscar-winning performances in "Good Will Hunting," Williams brought unparalleled energy, improvisation, and emotional depth to every role. His comedic genius and ability to shift seamlessly between humor and profound pathos touched the hearts of millions. Films like "Dead Poets Society," "Mrs. Doubtfire," and "Aladdin" remain beloved by audiences worldwide.',
            ],
            [
                'first_name' => 'David',
                'last_name' => 'Bowie',
                'born' => '1947-01-08',
                'died' => '2016-01-10',
                'birth_place' => 'Brixton, London, England',
                'death_place' => 'Manhattan, New York City, USA',
                'obituary' => 'David Bowie, born David Robert Jones, was an English singer-songwriter and actor who was a leading figure in the music industry for over five decades. His innovative work, distinctive voice, and alter egos — most notably Ziggy Stardust — challenged conventions and influenced generations of musicians. From "Space Oddity" to "Heroes" to "Blackstar," Bowie continually reinvented himself while maintaining an unmistakable artistic identity. He is regarded as one of the most influential musicians of the 20th century.',
            ],
            [
                'first_name' => 'Aretha',
                'last_name' => 'Franklin',
                'born' => '1942-03-25',
                'died' => '2018-08-16',
                'birth_place' => 'Memphis, Tennessee, USA',
                'death_place' => 'Detroit, Michigan, USA',
                'obituary' => 'Aretha Franklin was an American singer, songwriter, and pianist known as the "Queen of Soul." Her powerful voice and emotional delivery on songs like "Respect," "Natural Woman," and "Chain of Fools" made her one of the best-selling musical artists of all time. Franklin was the first woman inducted into the Rock and Roll Hall of Fame and received the Presidential Medal of Freedom. Her music became anthems for civil rights and women\'s empowerment.',
                'cemetery' => 'Woodlawn Cemetery',
                'cemetery_address' => '19975 Woodward Ave, Detroit, MI 48203, USA',
            ],
            [
                'first_name' => 'Nelson',
                'last_name' => 'Mandela',
                'born' => '1918-07-18',
                'died' => '2013-12-05',
                'birth_place' => 'Mvezo, Transkei, South Africa',
                'death_place' => 'Johannesburg, South Africa',
                'obituary' => 'Nelson Rolihlahla Mandela was a South African anti-apartheid revolutionary, political leader, and philanthropist who served as President of South Africa from 1994 to 1999. After 27 years of imprisonment, Mandela emerged without bitterness to lead his country toward reconciliation and democracy. Awarded the Nobel Peace Prize in 1993, he became a global symbol of resistance to oppression, forgiveness, and the enduring power of the human spirit.',
                'cemetery' => 'Mandela Gravesite',
                'cemetery_address' => 'Qunu, Eastern Cape, South Africa',
            ],
            [
                'first_name' => 'Prince',
                'last_name' => 'Rogers Nelson',
                'born' => '1958-06-07',
                'died' => '2016-04-21',
                'birth_place' => 'Minneapolis, Minnesota, USA',
                'death_place' => 'Chanhassen, Minnesota, USA',
                'obituary' => 'Prince Rogers Nelson, known mononymously as Prince, was an American singer-songwriter, musician, and producer. A musical prodigy who played 27 instruments, Prince blended funk, rock, R&B, pop, and new wave into a sound uniquely his own. "Purple Rain," "When Doves Cry," "Kiss," and "1999" are just a few of the iconic songs from his catalog of over 1,000 compositions. He won seven Grammy Awards, an Academy Award, and was inducted into the Rock and Roll Hall of Fame in 2004.',
                'cemetery' => 'Paisley Park Studios',
                'cemetery_address' => '7801 Audubon Rd, Chanhassen, MN 55317, USA',
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Jackson',
                'born' => '1958-08-29',
                'died' => '2009-06-25',
                'birth_place' => 'Gary, Indiana, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Michael Joseph Jackson was an American singer, songwriter, and dancer known as the "King of Pop." His contributions to music, dance, and fashion, along with his publicized personal life, made him a global figure in popular culture for over four decades. His music videos, including "Thriller," "Billie Jean," and "Beat It," elevated the art form to new heights. "Thriller" remains the best-selling album of all time with over 70 million copies sold.',
                'cemetery' => 'Forest Lawn Memorial Park',
                'cemetery_address' => '1712 S Glendale Ave, Glendale, CA 91205, USA',
            ],
            [
                'first_name' => 'Chadwick',
                'last_name' => 'Boseman',
                'born' => '1976-11-29',
                'died' => '2020-08-28',
                'birth_place' => 'Anderson, South Carolina, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Chadwick Aaron Boseman was an American actor who portrayed real-life historical icons Jackie Robinson, James Brown, and Thurgood Marshall. He achieved international fame as T\'Challa / Black Panther in the Marvel Cinematic Universe. "Black Panther" became a cultural phenomenon and symbol of Black excellence. Boseman privately battled colon cancer for four years while continuing to work, demonstrating extraordinary courage and dedication to his craft and his fans.',
            ],
            [
                'first_name' => 'Kobe',
                'last_name' => 'Bryant',
                'born' => '1978-08-23',
                'died' => '2020-01-26',
                'birth_place' => 'Philadelphia, Pennsylvania, USA',
                'death_place' => 'Calabasas, California, USA',
                'obituary' => 'Kobe Bean Bryant was an American professional basketball player who spent his entire 20-year career with the Los Angeles Lakers. A five-time NBA champion, two-time Finals MVP, and 18-time All-Star, Bryant was one of the greatest basketball players of all time. His relentless work ethic, known as the "Mamba Mentality," inspired athletes across all sports. After retirement, he won an Academy Award for his animated short film "Dear Basketball."',
                'cemetery' => 'Pacific View Memorial Park',
                'cemetery_address' => '3500 Pacific View Dr, Newport Beach, CA 92663, USA',
            ],
            [
                'first_name' => 'Stephen',
                'last_name' => 'Hawking',
                'born' => '1942-01-08',
                'died' => '2018-03-14',
                'birth_place' => 'Oxford, England',
                'death_place' => 'Cambridge, England',
                'obituary' => 'Stephen William Hawking was an English theoretical physicist, cosmologist, and author. Despite being diagnosed with amyotrophic lateral sclerosis (ALS) at age 21, he went on to become one of the most brilliant theoretical physicists since Einstein. His work on black holes and the origin of the universe, popularized in "A Brief History of Time," made complex science accessible to millions. Hawking proved that physical limitations need not limit the human mind.',
                'cemetery' => 'Westminster Abbey',
                'cemetery_address' => '20 Deans Yd, London SW1P 3PA, United Kingdom',
            ],
            [
                'first_name' => 'Ruth Bader',
                'last_name' => 'Ginsburg',
                'born' => '1933-03-15',
                'died' => '2020-09-18',
                'birth_place' => 'Brooklyn, New York, USA',
                'death_place' => 'Washington, D.C., USA',
                'obituary' => 'Ruth Bader Ginsburg was an American lawyer and jurist who served as an Associate Justice of the Supreme Court from 1993 until her death. Known as "The Notorious RBG," she was a champion of gender equality and civil rights. Her landmark cases and powerful dissents advanced the cause of justice in America. Ginsburg broke barriers throughout her career and became an icon for a new generation of activists and legal scholars.',
                'cemetery' => 'Arlington National Cemetery',
                'cemetery_address' => 'Arlington, VA 22211, USA',
            ],
            [
                'first_name' => 'Wolfgang Amadeus',
                'last_name' => 'Mozart',
                'born' => '1756-01-27',
                'died' => '1791-12-05',
                'birth_place' => 'Salzburg, Archbishopric of Salzburg',
                'death_place' => 'Vienna, Austria',
                'obituary' => 'Wolfgang Amadeus Mozart was a prolific and influential composer of the Classical period who composed over 800 works in virtually every genre of his time. A child prodigy who began performing at the age of five, Mozart created masterpieces including "The Marriage of Figaro," "Don Giovanni," "The Magic Flute," and his Requiem. His music, characterized by its melodic beauty, formal elegance, and emotional depth, continues to define Western classical music.',
                'cemetery' => 'St. Marx Cemetery',
                'cemetery_address' => 'Leberstraße 6-8, 1030 Vienna, Austria',
            ],
            [
                'first_name' => 'Ludwig van',
                'last_name' => 'Beethoven',
                'born' => '1770-12-17',
                'died' => '1827-03-26',
                'birth_place' => 'Bonn, Electorate of Cologne',
                'death_place' => 'Vienna, Austrian Empire',
                'obituary' => 'Ludwig van Beethoven was a German composer and pianist who was a crucial figure in the transition between the Classical and Romantic eras of Western music. Despite progressive hearing loss that eventually rendered him almost totally deaf, Beethoven produced some of the most celebrated compositions in history, including his nine symphonies, five piano concertos, and the "Moonlight Sonata." His Ninth Symphony, with its choral finale "Ode to Joy," stands as one of humanity\'s greatest artistic achievements.',
                'cemetery' => 'Zentralfriedhof',
                'cemetery_address' => 'Simmeringer Hauptstraße 234, 1110 Vienna, Austria',
            ],
            [
                'first_name' => 'Vincent',
                'last_name' => 'van Gogh',
                'born' => '1853-03-30',
                'died' => '1890-07-29',
                'birth_place' => 'Zundert, Netherlands',
                'death_place' => 'Auvers-sur-Oise, France',
                'obituary' => 'Vincent Willem van Gogh was a Dutch Post-Impressionist painter who posthumously became one of the most famous and influential figures in Western art history. In just over a decade, he created approximately 2,100 artworks, including "The Starry Night," "Sunflowers," and "Café Terrace at Night." His bold colors, dramatic brushwork, and emotional honesty influenced countless artists. Though he struggled with mental illness and poverty during his lifetime, his art now hangs in the world\'s greatest museums.',
                'cemetery' => 'Auvers-sur-Oise Cemetery',
                'cemetery_address' => 'Rue Émile Bernard, 95430 Auvers-sur-Oise, France',
            ],
            [
                'first_name' => 'Abraham',
                'last_name' => 'Lincoln',
                'born' => '1809-02-12',
                'died' => '1865-04-15',
                'birth_place' => 'Hodgenville, Kentucky, USA',
                'death_place' => 'Washington, D.C., USA',
                'obituary' => 'Abraham Lincoln was the 16th President of the United States, serving from 1861 until his assassination. He led the nation through the Civil War, preserved the Union, abolished slavery with the Emancipation Proclamation and the Thirteenth Amendment, and strengthened the federal government. Lincoln\'s Gettysburg Address redefined American democracy and remains one of the most quoted speeches in history. He is consistently ranked as one of the greatest American presidents.',
                'cemetery' => 'Lincoln Tomb',
                'cemetery_address' => '1500 Monument Ave, Springfield, IL 62702, USA',
            ],
            [
                'first_name' => 'Mahatma',
                'last_name' => 'Gandhi',
                'born' => '1869-10-02',
                'died' => '1948-01-30',
                'birth_place' => 'Porbandar, Gujarat, British India',
                'death_place' => 'New Delhi, India',
                'obituary' => 'Mohandas Karamchand Gandhi, known as Mahatma ("Great Soul"), was an Indian lawyer, anti-colonial nationalist, and political ethicist who led India to independence through nonviolent civil disobedience. His philosophy of peaceful resistance inspired civil rights and freedom movements across the world, influencing leaders like Martin Luther King Jr. and Nelson Mandela. Gandhi\'s commitment to truth, simplicity, and justice made him one of the most revered figures in modern history.',
                'cemetery' => 'Raj Ghat',
                'cemetery_address' => 'Raj Ghat, New Delhi, India',
            ],
            [
                'first_name' => 'Tupac',
                'last_name' => 'Shakur',
                'born' => '1971-06-16',
                'died' => '1996-09-13',
                'birth_place' => 'East Harlem, New York City, USA',
                'death_place' => 'Las Vegas, Nevada, USA',
                'obituary' => 'Tupac Amaru Shakur was an American rapper, songwriter, and actor considered one of the most influential and greatest hip-hop artists of all time. His music addressed contemporary social issues including racism, police brutality, poverty, and inequality. Albums like "All Eyez on Me" and "Me Against the World" showcased his poetic skill and emotional depth. Shakur sold over 75 million records worldwide, and his influence on hip-hop culture remains profound.',
            ],
            [
                'first_name' => 'Coco',
                'last_name' => 'Chanel',
                'born' => '1883-08-19',
                'died' => '1971-01-10',
                'birth_place' => 'Saumur, Maine-et-Loire, France',
                'death_place' => 'Paris, France',
                'obituary' => 'Gabrielle Bonheur "Coco" Chanel was a French fashion designer and businesswoman who founded the Chanel brand. She revolutionized women\'s fashion by introducing comfortable, casual elegance as an alternative to the corseted silhouette. Chanel popularized the little black dress, the Chanel suit, the quilted handbag, and Chanel No. 5 perfume. Her influence on 20th-century fashion is immeasurable, and the brand she created remains one of the most prestigious in the world.',
                'cemetery' => 'Bois-de-Vaux Cemetery',
                'cemetery_address' => 'Avenue du Bois-de-Vaux, 1007 Lausanne, Switzerland',
            ],
            [
                'first_name' => 'Bruce',
                'last_name' => 'Lee',
                'born' => '1940-11-27',
                'died' => '1973-07-20',
                'birth_place' => 'Chinatown, San Francisco, USA',
                'death_place' => 'Kowloon Tong, Hong Kong',
                'obituary' => 'Bruce Lee was a Hong Kong and American martial artist, actor, director, and philosopher. He is considered the most influential martial artist of all time and a pop culture icon of the 20th century. Lee\'s films, including "Enter the Dragon" and "Fist of Fury," broke barriers and bridged the gap between Eastern and Western cultures. His martial arts philosophy, Jeet Kune Do, emphasized adaptability and practical combat. Lee\'s influence extends far beyond martial arts into fitness, philosophy, and film.',
                'cemetery' => 'Lake View Cemetery',
                'cemetery_address' => '1554 15th Ave E, Seattle, WA 98112, USA',
            ],
            [
                'first_name' => 'Mother',
                'last_name' => 'Teresa',
                'born' => '1910-08-26',
                'died' => '1997-09-05',
                'birth_place' => 'Üsküb, Ottoman Empire (now Skopje)',
                'death_place' => 'Kolkata, India',
                'obituary' => 'Mother Teresa, born Anjezë Gonxhe Bojaxhiu, was an Albanian-Indian Roman Catholic nun and missionary who founded the Missionaries of Charity. For over 45 years, she ministered to the poor, sick, orphaned, and dying in Kolkata and around the world. Awarded the Nobel Peace Prize in 1979, she dedicated her life to serving "the poorest of the poor." She was canonized as Saint Teresa of Calcutta by Pope Francis in 2016.',
                'cemetery' => 'Mother House of the Missionaries of Charity',
                'cemetery_address' => '54A, A.J.C. Bose Road, Kolkata, India',
            ],
            [
                'first_name' => 'Walt',
                'last_name' => 'Disney',
                'born' => '1901-12-05',
                'died' => '1966-12-15',
                'birth_place' => 'Chicago, Illinois, USA',
                'death_place' => 'Burbank, California, USA',
                'obituary' => 'Walter Elias Disney was an American animator, film producer, and entrepreneur who co-founded The Walt Disney Company. A pioneer of the American animation industry, he introduced innovations in the production of cartoons and created Mickey Mouse, one of the most recognizable characters in the world. Disney\'s theme parks, films, and storytelling legacy have brought joy to billions of people across generations. He holds the record for most Academy Awards earned by an individual.',
                'cemetery' => 'Forest Lawn Memorial Park',
                'cemetery_address' => '1712 S Glendale Ave, Glendale, CA 91205, USA',
            ],
            [
                'first_name' => 'Johnny',
                'last_name' => 'Cash',
                'born' => '1932-02-26',
                'died' => '2003-09-12',
                'birth_place' => 'Kingsland, Arkansas, USA',
                'death_place' => 'Nashville, Tennessee, USA',
                'obituary' => 'John R. "Johnny" Cash was an American singer-songwriter and actor known as "The Man in Black." One of the best-selling music artists of all time, Cash\'s deep bass-baritone voice and songs of sorrow, moral tribulation, and redemption made him a towering figure in country, rock and roll, and folk music. His iconic hits include "Ring of Fire," "Folsom Prison Blues," and "I Walk the Line." Cash\'s authenticity and willingness to champion the downtrodden made him a cultural icon.',
                'cemetery' => 'Hendersonville Memory Gardens',
                'cemetery_address' => '353 E Main St, Hendersonville, TN 37075, USA',
            ],
            [
                'first_name' => 'John F.',
                'last_name' => 'Kennedy',
                'born' => '1917-05-29',
                'died' => '1963-11-22',
                'birth_place' => 'Brookline, Massachusetts, USA',
                'death_place' => 'Dallas, Texas, USA',
                'obituary' => 'John Fitzgerald Kennedy was the 35th President of the United States, serving from January 1961 until his assassination in November 1963. The youngest person elected president, JFK inspired a generation with his vision of public service, the Peace Corps, the space program, and his famous call: "Ask not what your country can do for you — ask what you can do for your country." His leadership during the Cuban Missile Crisis helped avert nuclear war.',
                'cemetery' => 'Arlington National Cemetery',
                'cemetery_address' => 'Arlington, VA 22211, USA',
            ],
            [
                'first_name' => 'Pablo',
                'last_name' => 'Picasso',
                'born' => '1881-10-25',
                'died' => '1973-04-08',
                'birth_place' => 'Málaga, Spain',
                'death_place' => 'Mougins, France',
                'obituary' => 'Pablo Ruiz Picasso was a Spanish painter, sculptor, printmaker, and ceramicist who is widely regarded as one of the most influential artists of the 20th century. Co-founder of Cubism, Picasso\'s prolific output over a career spanning 79 years produced an estimated 50,000 works of art. From the Blue Period to Guernica, his art reflected and shaped the century\'s most profound cultural shifts. Picasso remains a symbol of creative genius and artistic innovation.',
                'cemetery' => 'Château de Vauvenargues',
                'cemetery_address' => 'Vauvenargues, Bouches-du-Rhône, France',
            ],
            [
                'first_name' => 'Jimi',
                'last_name' => 'Hendrix',
                'born' => '1942-11-27',
                'died' => '1970-09-18',
                'birth_place' => 'Seattle, Washington, USA',
                'death_place' => 'London, England',
                'obituary' => 'James Marshall "Jimi" Hendrix was an American musician, singer, and songwriter who is widely regarded as the greatest electric guitarist in the history of popular music. In just four years of mainstream fame, Hendrix revolutionized the electric guitar with his innovative use of feedback, distortion, and wah-wah effects. His performances at Monterey and Woodstock are legendary, and songs like "Purple Haze," "Voodoo Child," and his rendition of "The Star-Spangled Banner" remain defining moments in rock history.',
                'cemetery' => 'Greenwood Memorial Park',
                'cemetery_address' => '350 Monroe Ave NE, Renton, WA 98056, USA',
            ],
            [
                'first_name' => 'Janis',
                'last_name' => 'Joplin',
                'born' => '1943-01-19',
                'died' => '1970-10-04',
                'birth_place' => 'Port Arthur, Texas, USA',
                'death_place' => 'Hollywood, California, USA',
                'obituary' => 'Janis Lyn Joplin was an American rock, soul, and blues singer-songwriter who was one of the most successful and widely known female rock stars of her era. Her raw, powerful, and emotionally charged vocal style made her one of the standout performers of the late 1960s. Songs like "Piece of My Heart," "Me and Bobby McGee," and "Cry Baby" showcased her extraordinary vocal talent. Joplin remains an icon of the counterculture movement and a symbol of artistic authenticity.',
            ],
            [
                'first_name' => 'Charlie',
                'last_name' => 'Chaplin',
                'born' => '1889-04-16',
                'died' => '1977-12-25',
                'birth_place' => 'London, England',
                'death_place' => 'Corsier-sur-Vevey, Switzerland',
                'obituary' => 'Sir Charles Spencer Chaplin was an English comic actor, filmmaker, and composer who rose to fame in the era of silent film. His iconic character "The Tramp" — with his bowler hat, mustache, baggy pants, and bamboo cane — became a universal symbol of humor and humanity. Chaplin\'s films, including "The Kid," "The Gold Rush," "City Lights," and "Modern Times," combined comedy with social commentary and remain masterpieces of cinema.',
                'cemetery' => 'Corsier-sur-Vevey Cemetery',
                'cemetery_address' => 'Corsier-sur-Vevey, Switzerland',
            ],
            [
                'first_name' => 'Billie',
                'last_name' => 'Holiday',
                'born' => '1915-04-07',
                'died' => '1959-07-17',
                'birth_place' => 'Philadelphia, Pennsylvania, USA',
                'death_place' => 'New York City, New York, USA',
                'obituary' => 'Billie Holiday, born Eleanora Fagan, was an American jazz and swing music singer. Nicknamed "Lady Day," she had a seminal influence on jazz music and pop singing. Her vocal style, inspired by jazz instrumentalists, pioneered a new way of manipulating phrasing and tempo. Songs like "Strange Fruit," "God Bless the Child," and "Lady Sings the Blues" showcase her extraordinary ability to convey deep emotion. Holiday is widely regarded as one of the greatest vocalists of all time.',
                'cemetery' => 'Saint Raymond\'s Cemetery',
                'cemetery_address' => '2600 Lafayette Ave, Bronx, NY 10465, USA',
            ],
            [
                'first_name' => 'Winston',
                'last_name' => 'Churchill',
                'born' => '1874-11-30',
                'died' => '1965-01-24',
                'birth_place' => 'Blenheim Palace, Oxfordshire, England',
                'death_place' => 'London, England',
                'obituary' => 'Sir Winston Leonard Spencer Churchill was a British statesman, soldier, and writer who served as Prime Minister of the United Kingdom from 1940 to 1945 and again from 1951 to 1955. His leadership during World War II rallied the British people and helped lead the Allied victory against Nazi Germany. Churchill\'s powerful oratory, including "We shall fight on the beaches" and "Their finest hour," inspired a nation in its darkest hour. He received the Nobel Prize in Literature in 1953.',
                'cemetery' => 'St Martin\'s Churchyard',
                'cemetery_address' => 'Bladon, Woodstock OX20 1RS, United Kingdom',
            ],
            [
                'first_name' => 'Notorious',
                'last_name' => 'B.I.G.',
                'born' => '1972-05-21',
                'died' => '1997-03-09',
                'birth_place' => 'Brooklyn, New York City, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Christopher George Latore Wallace, known as The Notorious B.I.G. or Biggie Smalls, was an American rapper widely considered one of the greatest and most influential rappers of all time. His storytelling ability, smooth flow, and vivid lyricism on albums "Ready to Die" and "Life After Death" defined East Coast hip-hop in the 1990s. Biggie\'s music continues to influence rap culture, and his legacy as a master lyricist endures decades after his untimely death.',
            ],
            [
                'first_name' => 'Luciano',
                'last_name' => 'Pavarotti',
                'born' => '1935-10-12',
                'died' => '2007-09-06',
                'birth_place' => 'Modena, Italy',
                'death_place' => 'Modena, Italy',
                'obituary' => 'Luciano Pavarotti was an Italian operatic tenor who became one of the most commercially successful tenors of all time. Known for his powerful voice, exceptional breath control, and the warmth of his performances, Pavarotti brought opera to mainstream audiences worldwide. As one of The Three Tenors alongside Plácido Domingo and José Carreras, he helped popularize classical music. His signature performance of "Nessun Dorma" remains one of the most recognized arias in the world.',
                'cemetery' => 'Montale Rangone Cemetery',
                'cemetery_address' => 'Castelnuovo Rangone, Modena, Italy',
            ],
            [
                'first_name' => 'Maya',
                'last_name' => 'Angelou',
                'born' => '1928-04-04',
                'died' => '2014-05-28',
                'birth_place' => 'St. Louis, Missouri, USA',
                'death_place' => 'Winston-Salem, North Carolina, USA',
                'obituary' => 'Maya Angelou was an American poet, memoirist, and civil rights activist. Her autobiography "I Know Why the Caged Bird Sings" brought her international recognition and acclaim. Angelou\'s powerful prose and poetry explored themes of identity, family, racism, and resilience. She recited her poem "On the Pulse of Morning" at President Bill Clinton\'s inauguration in 1993. Her words continue to inspire millions with their message of strength, dignity, and hope.',
            ],
            [
                'first_name' => 'Frank',
                'last_name' => 'Sinatra',
                'born' => '1915-12-12',
                'died' => '1998-05-14',
                'birth_place' => 'Hoboken, New Jersey, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Francis Albert Sinatra was an American singer and actor who is among the world\'s best-selling music artists of all time. Known as "Ol\' Blue Eyes" and "The Chairman of the Board," Sinatra\'s career spanned six decades. His impeccable phrasing and emotional depth on songs like "My Way," "Fly Me to the Moon," and "New York, New York" set the standard for popular vocalists. He also received the Academy Award for Best Supporting Actor for "From Here to Eternity."',
                'cemetery' => 'Desert Memorial Park',
                'cemetery_address' => '31705 Da Vall Dr, Cathedral City, CA 92234, USA',
            ],
            [
                'first_name' => 'Elizabeth',
                'last_name' => 'Taylor',
                'born' => '1932-02-27',
                'died' => '2011-03-23',
                'birth_place' => 'London, England',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Dame Elizabeth Rosemond Taylor was a British-American actress who was one of the great screen actresses of Hollywood\'s Golden Age. Known for her stunning beauty and violet eyes, Taylor starred in classics including "Cleopatra," "Cat on a Hot Tin Roof," and "Who\'s Afraid of Virginia Woolf?" She won two Academy Awards for Best Actress. Later in life, she became a passionate advocate for HIV/AIDS research, co-founding amfAR and raising millions for the cause.',
                'cemetery' => 'Forest Lawn Memorial Park',
                'cemetery_address' => '1712 S Glendale Ave, Glendale, CA 91205, USA',
            ],
            [
                'first_name' => 'Alexander',
                'last_name' => 'McQueen',
                'born' => '1969-03-17',
                'died' => '2010-02-11',
                'birth_place' => 'Lewisham, London, England',
                'death_place' => 'Mayfair, London, England',
                'obituary' => 'Lee Alexander McQueen was a British fashion designer and couturier. Known for his dramatic and provocative designs, McQueen combined masterful tailoring with raw emotional power. He served as chief designer at Givenchy before founding his own label. His runway shows were theatrical productions that pushed the boundaries of fashion as art. Named British Designer of the Year four times, McQueen\'s visionary work continues to influence the fashion world.',
            ],
            [
                'first_name' => 'Heath',
                'last_name' => 'Ledger',
                'born' => '1979-04-04',
                'died' => '2008-01-22',
                'birth_place' => 'Perth, Western Australia',
                'death_place' => 'Manhattan, New York City, USA',
                'obituary' => 'Heath Andrew Ledger was an Australian actor and director. After early roles in Australian television, he moved to Hollywood and received critical acclaim for "Brokeback Mountain" and "Monster\'s Ball." His portrayal of the Joker in "The Dark Knight" is widely regarded as one of the greatest performances in film history, earning him a posthumous Academy Award for Best Supporting Actor. Ledger\'s intense commitment to his craft and his extraordinary range left an enduring mark on cinema.',
            ],
            [
                'first_name' => 'Avicii',
                'last_name' => 'Bergling',
                'born' => '1989-09-08',
                'died' => '2018-04-20',
                'birth_place' => 'Stockholm, Sweden',
                'death_place' => 'Muscat, Oman',
                'obituary' => 'Tim Bergling, known professionally as Avicii, was a Swedish DJ, musician, and songwriter who became one of the defining artists of the electronic dance music revolution. His hits "Levels," "Wake Me Up," and "Hey Brother" brought EDM into the global mainstream and topped charts worldwide. Avicii\'s melodic approach to electronic music, blending folk, country, and bluegrass elements, created a signature sound that influenced a generation of producers and musicians.',
            ],
            [
                'first_name' => 'Aaliyah',
                'last_name' => 'Haughton',
                'born' => '1979-01-16',
                'died' => '2001-08-25',
                'birth_place' => 'Brooklyn, New York City, USA',
                'death_place' => 'Marsh Harbour, Bahamas',
                'obituary' => 'Aaliyah Dana Haughton was an American singer, actress, and model. She has been credited for helping to redefine R&B, pop, and hip-hop in the 1990s and 2000s. Her albums "One in a Million" and "Aaliyah" showcased a distinctive style that blended silky vocals with innovative production. Known as the "Princess of R&B," Aaliyah\'s influence on contemporary R&B music and fashion endures. She also appeared in films "Romeo Must Die" and "Queen of the Damned."',
                'cemetery' => 'Ferncliff Cemetery',
                'cemetery_address' => '280 Secor Rd, Hartsdale, NY 10530, USA',
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Dean',
                'born' => '1931-02-08',
                'died' => '1955-09-30',
                'birth_place' => 'Marion, Indiana, USA',
                'death_place' => 'Cholame, California, USA',
                'obituary' => 'James Byron Dean was an American actor who became a cultural icon of teenage disillusionment and social estrangement. Despite a career spanning only three major films — "East of Eden," "Rebel Without a Cause," and "Giant" — Dean\'s intense and emotional performances captured the restless spirit of postwar American youth. He received two posthumous Academy Award nominations and remains a symbol of youthful rebellion and raw artistic talent.',
                'cemetery' => 'Park Cemetery',
                'cemetery_address' => 'Fairmount, IN 46928, USA',
            ],
            [
                'first_name' => 'Grace',
                'last_name' => 'Kelly',
                'born' => '1929-11-12',
                'died' => '1982-09-14',
                'birth_place' => 'Philadelphia, Pennsylvania, USA',
                'death_place' => 'Monaco',
                'obituary' => 'Grace Patricia Kelly was an American actress who became Princess of Monaco after marrying Prince Rainier III in 1956. Before her royal life, she was one of Hollywood\'s most elegant leading ladies, starring in Hitchcock classics "Rear Window," "Dial M for Murder," and "To Catch a Thief." She won the Academy Award for Best Actress for "The Country Girl." Kelly epitomized grace and sophistication both on screen and as a princess.',
                'cemetery' => 'Cathedral of Our Lady Immaculate',
                'cemetery_address' => '98000 Monaco',
            ],
            [
                'first_name' => 'Ray',
                'last_name' => 'Charles',
                'born' => '1930-09-23',
                'died' => '2004-06-10',
                'birth_place' => 'Albany, Georgia, USA',
                'death_place' => 'Beverly Hills, California, USA',
                'obituary' => 'Ray Charles Robinson was an American singer, songwriter, musician, and composer who pioneered the soul music genre by combining blues, jazz, rhythm and blues, and gospel styles. Known as "The Genius," his recordings of "Georgia on My Mind," "Hit the Road Jack," and "I Got a Woman" broke racial and musical barriers. Despite losing his sight at age seven, Charles became one of the most influential musicians of the 20th century, winning 17 Grammy Awards.',
                'cemetery' => 'Inglewood Park Cemetery',
                'cemetery_address' => '720 E Florence Ave, Inglewood, CA 90301, USA',
            ],
            [
                'first_name' => 'Amelia',
                'last_name' => 'Earhart',
                'born' => '1897-07-24',
                'died' => '1937-07-02',
                'birth_place' => 'Atchison, Kansas, USA',
                'death_place' => 'Pacific Ocean (declared dead)',
                'obituary' => 'Amelia Mary Earhart was an American aviation pioneer and author. The first female aviator to fly solo across the Atlantic Ocean, she set numerous other records and championed the advancement of women in aviation. Her courage, determination, and trailblazing spirit inspired generations of women to pursue their dreams. Earhart\'s disappearance over the Pacific Ocean during her attempt to circumnavigate the globe in 1937 remains one of the greatest unsolved mysteries of the 20th century.',
            ],
            [
                'first_name' => 'Bob',
                'last_name' => 'Ross',
                'born' => '1942-10-29',
                'died' => '1995-07-04',
                'birth_place' => 'Daytona Beach, Florida, USA',
                'death_place' => 'New Smyrna Beach, Florida, USA',
                'obituary' => 'Robert Norman Ross was an American painter and television host best known for his instructional show "The Joy of Painting," which ran from 1983 to 1994. With his gentle voice, iconic afro, and philosophy of "happy little trees" and "happy accidents," Ross made painting accessible and joyful for millions of viewers. His calming presence and encouraging words have found new audiences through the internet, making him a beloved cultural figure across generations.',
            ],
            [
                'first_name' => 'Anne',
                'last_name' => 'Frank',
                'born' => '1929-06-12',
                'died' => '1945-02-01',
                'birth_place' => 'Frankfurt, Germany',
                'death_place' => 'Bergen-Belsen concentration camp, Germany',
                'obituary' => 'Annelies Marie Frank was a German-Dutch diarist and writer. One of the most discussed Jewish victims of the Holocaust, she gained fame posthumously with the publication of "The Diary of a Young Girl," which documents her life in hiding from 1942 to 1944 during the German occupation of the Netherlands. Her diary, translated into over 70 languages, provides a powerful, intimate account of life under persecution and stands as a testament to the human spirit in the face of unimaginable adversity.',
            ],
            [
                'first_name' => 'Andy',
                'last_name' => 'Warhol',
                'born' => '1928-08-06',
                'died' => '1987-02-22',
                'birth_place' => 'Pittsburgh, Pennsylvania, USA',
                'death_place' => 'Manhattan, New York City, USA',
                'obituary' => 'Andy Warhol was an American visual artist, film director, and producer who was a leading figure in the Pop Art movement. His works explored celebrity culture, consumer society, and the relationship between artistic expression and advertising. Iconic pieces like the Campbell\'s Soup Cans, Marilyn Monroe portraits, and Brillo Boxes challenged traditional notions of art. Warhol\'s Factory studio became a cultural hub, and his prediction that "everyone will be world-famous for 15 minutes" proved prophetic.',
                'cemetery' => 'St. John the Baptist Byzantine Catholic Cemetery',
                'cemetery_address' => 'Bethel Park, PA 15102, USA',
            ],
            [
                'first_name' => 'Selena',
                'last_name' => 'Quintanilla',
                'born' => '1971-04-16',
                'died' => '1995-03-31',
                'birth_place' => 'Lake Jackson, Texas, USA',
                'death_place' => 'Corpus Christi, Texas, USA',
                'obituary' => 'Selena Quintanilla-Pérez was an American Tejano music singer, songwriter, and fashion designer. Called the "Queen of Tejano Music," she was one of the most celebrated Mexican-American entertainers of the late 20th century. Her album "Dreaming of You" became the first Tejano record to debut at number one on the Billboard 200. Selena\'s infectious energy, powerful voice, and cross-cultural appeal made her a beloved figure whose legacy continues to inspire Latinx communities worldwide.',
                'cemetery' => 'Seaside Memorial Park',
                'cemetery_address' => '4357 Ocean Dr, Corpus Christi, TX 78412, USA',
            ],
            [
                'first_name' => 'Nikki',
                'last_name' => 'Lauda',
                'born' => '1949-02-22',
                'died' => '2019-05-20',
                'birth_place' => 'Vienna, Austria',
                'death_place' => 'Zürich, Switzerland',
                'obituary' => 'Andreas Nikolaus "Niki" Lauda was an Austrian Formula One driver and aviation entrepreneur who is widely regarded as one of the greatest F1 drivers in history. He won three World Championships (1975, 1977, 1984) and is renowned for his remarkable comeback after a horrific crash at the Nürburgring in 1976 that left him with severe burns. Lauda\'s determination, technical intelligence, and competitive spirit defined an era of Formula One racing.',
            ],
            [
                'first_name' => 'Ayrton',
                'last_name' => 'Senna',
                'born' => '1960-03-21',
                'died' => '1994-05-01',
                'birth_place' => 'São Paulo, Brazil',
                'death_place' => 'Bologna, Italy',
                'obituary' => 'Ayrton Senna da Silva was a Brazilian racing driver who won three Formula One World Championships. Widely regarded as one of the greatest F1 drivers of all time, Senna was known for his aggressive racing style, exceptional skill in wet conditions, and intense rivalry with Alain Prost. His 65 pole positions stood as a record for years. In Brazil, Senna is a national hero whose legacy transcends motorsport, symbolizing passion, excellence, and determination.',
                'cemetery' => 'Morumbi Cemetery',
                'cemetery_address' => 'São Paulo, Brazil',
            ],
            [
                'first_name' => 'River',
                'last_name' => 'Phoenix',
                'born' => '1970-08-23',
                'died' => '1993-10-31',
                'birth_place' => 'Madras, Oregon, USA',
                'death_place' => 'West Hollywood, California, USA',
                'obituary' => 'River Jude Phoenix was an American actor, musician, and activist. Recognized for his versatile acting, Phoenix earned critical acclaim for roles in "Stand by Me," "My Own Private Idaho," and "Running on Empty," the latter earning him an Academy Award nomination at age 18. A dedicated environmentalist and animal rights activist, Phoenix was also a talented musician. His extraordinary talent and compassionate nature left an indelible impression on cinema and activism.',
            ],
            [
                'first_name' => 'Harriet',
                'last_name' => 'Tubman',
                'born' => '1822-03-01',
                'died' => '1913-03-10',
                'birth_place' => 'Dorchester County, Maryland, USA',
                'death_place' => 'Auburn, New York, USA',
                'obituary' => 'Harriet Tubman, born Araminta Ross, was an American abolitionist and political activist. After escaping from slavery, she made some 13 missions to rescue approximately 70 enslaved people using the network of antislavery activists and safe houses known as the Underground Railroad. During the Civil War, she served as an armed scout and spy for the Union Army. Tubman is an American icon of courage, freedom, and resistance against oppression.',
                'cemetery' => 'Fort Hill Cemetery',
                'cemetery_address' => '19 Fort St, Auburn, NY 13021, USA',
            ],
            [
                'first_name' => 'Virgil',
                'last_name' => 'Abloh',
                'born' => '1980-09-30',
                'died' => '2021-11-28',
                'birth_place' => 'Rockford, Illinois, USA',
                'death_place' => 'Chicago, Illinois, USA',
                'obituary' => 'Virgil Abloh was an American fashion designer, entrepreneur, and DJ who served as the artistic director of Louis Vuitton\'s menswear collection and founded the fashion label Off-White. A trained architect, Abloh brought a multidisciplinary approach to fashion that blurred the lines between streetwear and high fashion. He was the first African American to be appointed artistic director at a major French fashion house. Abloh\'s work redefined modern fashion and inspired a new generation of creatives.',
            ],
            [
                'first_name' => 'Juice',
                'last_name' => 'WRLD',
                'born' => '1998-12-02',
                'died' => '2019-12-08',
                'birth_place' => 'Chicago, Illinois, USA',
                'death_place' => 'Chicago, Illinois, USA',
                'obituary' => 'Jarad Anthony Higgins, known professionally as Juice WRLD, was an American rapper, singer, and songwriter who became one of the leading figures of the emo rap and SoundCloud rap genres. His debut single "Lucid Dreams" reached number two on the Billboard Hot 100, and his albums "Goodbye & Good Riddance" and "Death Race for Love" received widespread critical acclaim. Juice WRLD\'s raw emotional honesty in his music resonated deeply with a generation of young listeners.',
            ],
            [
                'first_name' => 'Nipsey',
                'last_name' => 'Hussle',
                'born' => '1985-08-15',
                'died' => '2019-03-31',
                'birth_place' => 'Los Angeles, California, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Ermias Joseph Asghedom, known as Nipsey Hussle, was an American rapper, songwriter, activist, and entrepreneur. His Grammy-nominated album "Victory Lap" cemented his place in hip-hop, but it was his community activism that defined his legacy. Hussle invested in his South Los Angeles neighborhood, opening businesses, creating STEM programs for youth, and working to end gang violence. He received a posthumous Grammy Award and is remembered as a community hero and visionary.',
            ],
            [
                'first_name' => 'Mac',
                'last_name' => 'Miller',
                'born' => '1992-01-19',
                'died' => '2018-09-07',
                'birth_place' => 'Pittsburgh, Pennsylvania, USA',
                'death_place' => 'Studio City, California, USA',
                'obituary' => 'Malcolm James McCormick, known professionally as Mac Miller, was an American rapper, singer, and record producer. Starting his career as a teen, Miller evolved from frat-rap beginnings to become one of his generation\'s most thoughtful and musically ambitious artists. Albums like "Swimming" and the posthumous "Circles" revealed a deeply introspective artist exploring jazz, soul, and psychedelia. Miller\'s honesty about his struggles with mental health connected deeply with his devoted fanbase.',
            ],
            [
                'first_name' => 'Carrie',
                'last_name' => 'Fisher',
                'born' => '1956-10-21',
                'died' => '2016-12-27',
                'birth_place' => 'Beverly Hills, California, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Carrie Frances Fisher was an American actress, writer, and comedian. She is best known for playing Princess Leia in the Star Wars film series, a role that made her one of the most recognizable figures in pop culture. Beyond acting, Fisher was a celebrated author and screenwriter, known for her semi-autobiographical novel "Postcards from the Edge." Her candid advocacy for mental health awareness and her sharp wit made her a beloved figure both on and off screen.',
                'cemetery' => 'Forest Lawn Memorial Park',
                'cemetery_address' => '6300 Forest Lawn Dr, Los Angeles, CA 90068, USA',
            ],
            [
                'first_name' => 'Philip Seymour',
                'last_name' => 'Hoffman',
                'born' => '1967-07-23',
                'died' => '2014-02-02',
                'birth_place' => 'Fairport, New York, USA',
                'death_place' => 'Manhattan, New York City, USA',
                'obituary' => 'Philip Seymour Hoffman was an American actor, director, and producer widely regarded as one of the finest actors of his generation. His Oscar-winning portrayal of Truman Capote in "Capote" demonstrated his ability to completely inhabit a character. Hoffman\'s extraordinary range encompassed both blockbusters and independent cinema, with memorable performances in "The Big Lebowski," "Boogie Nights," "Doubt," and "The Master." His dedication to his craft set a standard for acting excellence.',
            ],
            [
                'first_name' => 'Anthony',
                'last_name' => 'Bourdain',
                'born' => '1956-06-25',
                'died' => '2018-06-08',
                'birth_place' => 'New York City, New York, USA',
                'death_place' => 'Strasbourg, France',
                'obituary' => 'Anthony Michael Bourdain was an American celebrity chef, author, travel documentarian, and television personality. His bestselling book "Kitchen Confidential" and his television series "No Reservations" and "Parts Unknown" transformed food television by combining culinary exploration with cultural storytelling and genuine human connection. Bourdain\'s curiosity, honesty, and empathy for people from all walks of life made him one of the most influential voices in food, travel, and media.',
            ],
            [
                'first_name' => 'Stan',
                'last_name' => 'Lee',
                'born' => '1922-12-28',
                'died' => '2018-11-12',
                'birth_place' => 'Manhattan, New York City, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Stanley Martin Lieber, known as Stan Lee, was an American comic book writer, editor, publisher, and producer. As the creative leader of Marvel Comics, Lee co-created iconic superheroes including Spider-Man, the X-Men, Iron Man, the Hulk, Thor, and the Fantastic Four. His characters revolutionized comics by featuring flawed, relatable heroes dealing with real-world problems. Lee\'s vision laid the foundation for the Marvel Cinematic Universe and transformed popular culture worldwide.',
            ],
            [
                'first_name' => 'Alan',
                'last_name' => 'Rickman',
                'born' => '1946-02-21',
                'died' => '2016-01-14',
                'birth_place' => 'Hammersmith, London, England',
                'death_place' => 'London, England',
                'obituary' => 'Alan Sidney Patrick Rickman was an English actor and director known for his distinctive baritone voice and scene-stealing performances. From Hans Gruber in "Die Hard" to Professor Severus Snape in the Harry Potter series, Rickman brought intelligence, depth, and nuance to every role. His acclaimed stage career with the Royal Shakespeare Company and his film roles in "Sense and Sensibility," "Love Actually," and "Truly, Madly, Deeply" cemented his status as one of Britain\'s finest actors.',
                'cemetery' => 'Kensal Green Cemetery',
                'cemetery_address' => 'Harrow Rd, London W10 4RA, United Kingdom',
            ],
            [
                'first_name' => 'Paul',
                'last_name' => 'Walker',
                'born' => '1973-09-12',
                'died' => '2013-11-30',
                'birth_place' => 'Glendale, California, USA',
                'death_place' => 'Valencia, California, USA',
                'obituary' => 'Paul William Walker IV was an American actor best known for his role as Brian O\'Conner in "The Fast and the Furious" film series. His natural charisma and easygoing screen presence made him a fan favorite. Beyond Hollywood, Walker was a passionate marine biologist and dedicated philanthropist who founded Reach Out Worldwide, a disaster relief organization. His dedication to helping others and his genuine kindness left a legacy that extends far beyond his film career.',
                'cemetery' => 'Forest Lawn Memorial Park',
                'cemetery_address' => '1712 S Glendale Ave, Glendale, CA 91205, USA',
            ],
            [
                'first_name' => 'Leonard',
                'last_name' => 'Cohen',
                'born' => '1934-09-21',
                'died' => '2016-11-07',
                'birth_place' => 'Montreal, Quebec, Canada',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Leonard Norman Cohen was a Canadian singer-songwriter, poet, and novelist. His work explored religion, politics, isolation, depression, sexuality, loss, death, and romantic relationships. Songs like "Hallelujah," "Suzanne," "Bird on the Wire," and "Dance Me to the End of Love" are regarded as masterpieces of songwriting. Cohen\'s deep, unmistakable voice and literary approach to songwriting made him one of the most influential and revered artists of the 20th and 21st centuries.',
                'cemetery' => 'Shaar Hashomayim Cemetery',
                'cemetery_address' => 'Montreal, Quebec, Canada',
            ],
            [
                'first_name' => 'Donna',
                'last_name' => 'Summer',
                'born' => '1948-12-31',
                'died' => '2012-05-17',
                'birth_place' => 'Boston, Massachusetts, USA',
                'death_place' => 'Naples, Florida, USA',
                'obituary' => 'LaDonna Adrian Gaines, known as Donna Summer, was an American singer and songwriter who became known as the "Queen of Disco" during the 1970s. Her hits "I Feel Love," "Hot Stuff," "Last Dance," and "Bad Girls" defined the disco era and influenced the development of electronic dance music. Summer was the first artist to have three consecutive double albums reach number one on the Billboard chart. Her powerful voice and innovative music left an indelible mark on popular culture.',
            ],
            [
                'first_name' => 'George',
                'last_name' => 'Harrison',
                'born' => '1943-02-25',
                'died' => '2001-11-29',
                'birth_place' => 'Liverpool, England',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'George Harrison was an English musician, singer-songwriter, and music and film producer who achieved international fame as the lead guitarist of the Beatles. Known as "the quiet Beatle," Harrison\'s songwriting contributions included "Something," "Here Comes the Sun," and "While My Guitar Gently Weeps." His solo career produced the acclaimed triple album "All Things Must Pass." Harrison\'s introduction of Indian classical music to Western audiences and his devotion to spiritual exploration made him a unique cultural figure.',
            ],
            [
                'first_name' => 'Natasha',
                'last_name' => 'Richardson',
                'born' => '1963-05-11',
                'died' => '2009-03-18',
                'birth_place' => 'London, England',
                'death_place' => 'New York City, New York, USA',
                'obituary' => 'Natasha Jane Richardson was a British-American actress from one of Britain\'s most distinguished acting dynasties. The daughter of Vanessa Redgrave and director Tony Richardson, she won a Tony Award for her role in "Cabaret" on Broadway. Her film roles in "The Parent Trap," "Nell," and "Asylum" showcased her versatile talent. Richardson\'s warmth, intelligence, and dedication to her craft earned her admiration from audiences and fellow actors alike.',
            ],
            [
                'first_name' => 'XXXTentacion',
                'last_name' => 'Onfroy',
                'born' => '1998-01-23',
                'died' => '2018-06-18',
                'birth_place' => 'Plantation, Florida, USA',
                'death_place' => 'Deerfield Beach, Florida, USA',
                'obituary' => 'Jahseh Dwayne Ricardo Onfroy, known as XXXTentacion, was an American rapper and singer-songwriter who emerged as one of the most streamed artists of his generation. His album "17" explored themes of depression, loneliness, and heartbreak with raw vulnerability. Tracks like "SAD!" and "Moonlight" resonated deeply with young listeners navigating mental health challenges. His music blended hip-hop, rock, R&B, and lo-fi into something entirely his own.',
            ],
            [
                'first_name' => 'Brittany',
                'last_name' => 'Murphy',
                'born' => '1977-11-10',
                'died' => '2009-12-20',
                'birth_place' => 'Atlanta, Georgia, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Brittany Anne Murphy was an American actress and singer known for her distinctive voice and versatile performances. She rose to fame with her role as Tai in "Clueless" and went on to star in "Girl, Interrupted," "8 Mile," "Sin City," and "Just Married." Murphy also lent her voice to animated projects including Luanne Platter in "King of the Hill." Her natural charm and comedic timing made her one of Hollywood\'s most endearing young actresses.',
            ],
            [
                'first_name' => 'Patrick',
                'last_name' => 'Swayze',
                'born' => '1952-08-18',
                'died' => '2009-09-14',
                'birth_place' => 'Houston, Texas, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Patrick Wayne Swayze was an American actor, dancer, singer, and songwriter. His breakout roles in "Dirty Dancing" and "Ghost" made him one of the most popular leading men of the late 1980s and early 1990s. A trained dancer and athlete, Swayze brought physical grace and emotional intensity to his performances. His tough-but-tender screen presence in films like "Point Break" and "Road House" created an enduring legacy in popular culture.',
            ],
            [
                'first_name' => 'Tina',
                'last_name' => 'Turner',
                'maiden_name' => 'Bullock',
                'born' => '1939-11-26',
                'died' => '2023-05-24',
                'birth_place' => 'Brownsville, Tennessee, USA',
                'death_place' => 'Küsnacht, Switzerland',
                'obituary' => 'Anna Mae Bullock, known as Tina Turner, was an American-born Swiss singer, songwriter, and actress. Known as the "Queen of Rock \'n\' Roll," Turner\'s career spanned more than 60 years. Her powerful voice, electrifying stage presence, and hits like "What\'s Love Got to Do with It," "Proud Mary," and "Simply the Best" made her one of the best-selling recording artists of all time. Her story of survival and triumph over adversity inspired millions worldwide.',
                'cemetery' => 'Küsnacht Cemetery',
                'cemetery_address' => 'Küsnacht, Zürich, Switzerland',
            ],
            [
                'first_name' => 'Matthew',
                'last_name' => 'Perry',
                'born' => '1969-08-19',
                'died' => '2023-10-28',
                'birth_place' => 'Williamstown, Massachusetts, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Matthew Langford Perry was an American-Canadian actor, comedian, and playwright best known for his iconic role as Chandler Bing on the television sitcom "Friends." His impeccable comedic timing and delivery of sarcastic one-liners made Chandler one of the most beloved characters in television history. Perry was also a passionate advocate for addiction recovery, sharing his own struggles to help others. His memoir "Friends, Lovers, and the Big Terrible Thing" became a bestseller.',
                'cemetery' => 'Forest Lawn Memorial Park',
                'cemetery_address' => '6300 Forest Lawn Dr, Los Angeles, CA 90068, USA',
            ],
            [
                'first_name' => 'Lisa Marie',
                'last_name' => 'Presley',
                'born' => '1968-02-01',
                'died' => '2023-01-12',
                'birth_place' => 'Memphis, Tennessee, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Lisa Marie Presley was an American singer-songwriter and the only child of Elvis and Priscilla Presley. Growing up in the shadow of her father\'s immense legacy, she forged her own path in music with albums including "To Whom It May Concern" and "Storm & Grace." As the sole heir to the Presley estate, she was instrumental in preserving Graceland and her father\'s legacy. Her warmth, resilience, and artistic spirit defined a life lived both in and beyond the spotlight.',
                'cemetery' => 'Graceland',
                'cemetery_address' => '3764 Elvis Presley Blvd, Memphis, TN 38116, USA',
            ],
            [
                'first_name' => 'Sinéad',
                'last_name' => 'O\'Connor',
                'born' => '1966-12-08',
                'died' => '2023-07-26',
                'birth_place' => 'Dublin, Ireland',
                'death_place' => 'London, England',
                'obituary' => 'Sinéad Marie Bernadette O\'Connor was an Irish singer-songwriter who rose to worldwide fame with her version of Prince\'s "Nothing Compares 2 U." Known for her powerful voice, shaved head, and fierce independence, O\'Connor was unafraid to speak her mind on issues of religion, politics, and social justice. Her debut album "The Lion and the Cobra" and its follow-up "I Do Not Want What I Haven\'t Got" established her as one of the most distinctive artists of her generation.',
            ],
            [
                'first_name' => 'Coolio',
                'last_name' => 'Ivey',
                'born' => '1963-08-01',
                'died' => '2022-09-28',
                'birth_place' => 'Monessen, Pennsylvania, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Artis Leon Ivey Jr., known as Coolio, was an American rapper, singer, and actor who achieved mainstream success in the 1990s. His signature hit "Gangsta\'s Paradise," featured in the film "Dangerous Minds," became one of the best-selling singles of all time and won a Grammy Award. With his distinctive dreadlocks and crossover appeal, Coolio brought West Coast hip-hop to a global audience. His music blended rap with funk and soul for an unmistakable sound.',
            ],
            [
                'first_name' => 'Diego',
                'last_name' => 'Maradona',
                'born' => '1960-10-30',
                'died' => '2020-11-25',
                'birth_place' => 'Lanús, Buenos Aires, Argentina',
                'death_place' => 'Tigre, Buenos Aires, Argentina',
                'obituary' => 'Diego Armando Maradona was an Argentine professional football player and manager who is widely regarded as one of the greatest football players of all time. His "Hand of God" and "Goal of the Century" in the 1986 World Cup quarter-final are among the most famous moments in sports history. Maradona led Argentina to World Cup victory that year and transformed Napoli into a force in Italian football. His dazzling skill and passion for the game made him a global sporting icon.',
                'cemetery' => 'Jardín Bella Vista Cemetery',
                'cemetery_address' => 'Buenos Aires, Argentina',
            ],
            [
                'first_name' => 'Pelé',
                'last_name' => 'Nascimento',
                'born' => '1940-10-23',
                'died' => '2022-12-29',
                'birth_place' => 'Três Corações, Minas Gerais, Brazil',
                'death_place' => 'São Paulo, Brazil',
                'obituary' => 'Edson Arantes do Nascimento, known as Pelé, was a Brazilian professional footballer widely regarded as the greatest player of all time. The only player to win three FIFA World Cups (1958, 1962, 1970), Pelé scored over 1,000 career goals and brought the beautiful game to audiences worldwide. His extraordinary skill, creativity, and sportsmanship made him a global ambassador for football. Pelé\'s name became synonymous with excellence in sport.',
                'cemetery' => 'Memorial Necrópole Ecumênica',
                'cemetery_address' => 'Santos, São Paulo, Brazil',
            ],
            [
                'first_name' => 'Queen Elizabeth',
                'last_name' => 'II',
                'born' => '1926-04-21',
                'died' => '2022-09-08',
                'birth_place' => 'Mayfair, London, England',
                'death_place' => 'Balmoral Castle, Aberdeenshire, Scotland',
                'obituary' => 'Queen Elizabeth II was Queen of the United Kingdom and other Commonwealth realms from 1952 until her death, making her the longest-reigning British monarch in history. Over her 70-year reign, she witnessed enormous social change and served as a stabilizing figure through wars, political upheaval, and cultural transformation. Her dedication to duty, dignified service, and quiet strength earned her respect and admiration around the world.',
                'cemetery' => 'King George VI Memorial Chapel',
                'cemetery_address' => 'Windsor Castle, Windsor SL4 1NJ, United Kingdom',
            ],
            [
                'first_name' => 'Betty',
                'last_name' => 'White',
                'born' => '1922-01-17',
                'died' => '2021-12-31',
                'birth_place' => 'Oak Park, Illinois, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Betty Marion White was an American actress, comedian, and television pioneer whose career spanned over 80 years. Best known for her roles as Rose Nylund on "The Golden Girls" and Sue Ann Nivens on "The Mary Tyler Moore Show," White held the Guinness World Record for the longest television career by a female entertainer. Her warmth, wit, and dedication to animal welfare made her one of America\'s most beloved and enduring entertainment figures.',
            ],
            [
                'first_name' => 'Sidney',
                'last_name' => 'Poitier',
                'born' => '1927-02-20',
                'died' => '2022-01-06',
                'birth_place' => 'Miami, Florida, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Sir Sidney Poitier was a Bahamian-American actor and diplomat who became the first African American to win the Academy Award for Best Actor for his role in "Lilies of the Field" (1963). His powerful performances in "In the Heat of the Night," "Guess Who\'s Coming to Dinner," and "A Raisin in the Sun" broke racial barriers and challenged Hollywood\'s status quo. Poitier\'s dignity, talent, and courage paved the way for generations of Black actors.',
            ],
            [
                'first_name' => 'Mikhail',
                'last_name' => 'Gorbachev',
                'born' => '1931-03-02',
                'died' => '2022-08-30',
                'birth_place' => 'Privolnoye, Stavropol Krai, Soviet Union',
                'death_place' => 'Moscow, Russia',
                'obituary' => 'Mikhail Sergeyevich Gorbachev was a Soviet and Russian politician who served as the last leader of the Soviet Union from 1985 to 1991. His policies of glasnost (openness) and perestroika (restructuring) transformed the Soviet Union and helped end the Cold War. Awarded the Nobel Peace Prize in 1990, Gorbachev\'s reforms led to the dissolution of the Soviet Union and the liberation of Eastern Europe. His courage in pursuing peaceful change altered the course of world history.',
            ],
            [
                'first_name' => 'Desmond',
                'last_name' => 'Tutu',
                'born' => '1931-10-07',
                'died' => '2021-12-26',
                'birth_place' => 'Klerksdorp, Transvaal, South Africa',
                'death_place' => 'Cape Town, South Africa',
                'obituary' => 'Desmond Mpilo Tutu was a South African Anglican cleric and theologian who served as Archbishop of Cape Town. A leading figure in the struggle against apartheid, Tutu was awarded the Nobel Peace Prize in 1984 for his nonviolent campaign against racial injustice. As chairman of the Truth and Reconciliation Commission, he guided South Africa through a peaceful transition. Tutu\'s moral authority, infectious laughter, and unwavering commitment to human dignity inspired people worldwide.',
                'cemetery' => 'St George\'s Cathedral',
                'cemetery_address' => 'Wale St, Cape Town, South Africa',
            ],
            [
                'first_name' => 'Madeleine',
                'last_name' => 'Albright',
                'maiden_name' => 'Korbelová',
                'born' => '1937-05-15',
                'died' => '2022-03-23',
                'birth_place' => 'Prague, Czechoslovakia',
                'death_place' => 'Washington, D.C., USA',
                'obituary' => 'Madeleine Jana Korbel Albright was an American diplomat and political scientist who served as the 64th United States Secretary of State from 1997 to 2001, becoming the first woman to hold that position. Born in Czechoslovakia, she fled both Nazism and Communism before becoming one of America\'s most influential foreign policy voices. Albright\'s intellect, determination, and advocacy for democracy and human rights left a lasting impact on international diplomacy.',
                'cemetery' => 'Washington National Cathedral',
                'cemetery_address' => '3101 Wisconsin Ave NW, Washington, DC 20016, USA',
            ],
            [
                'first_name' => 'Meat',
                'last_name' => 'Loaf',
                'born' => '1947-09-27',
                'died' => '2022-01-20',
                'birth_place' => 'Dallas, Texas, USA',
                'death_place' => 'Nashville, Tennessee, USA',
                'obituary' => 'Marvin Lee Aday, known as Meat Loaf, was an American singer, songwriter, and actor. His album "Bat Out of Hell" is one of the best-selling albums of all time, with over 43 million copies sold worldwide. His operatic rock ballads, theatrical performances, and powerful voice — showcased on hits like "I\'d Do Anything for Love (But I Won\'t Do That)" and "Paradise by the Dashboard Light" — made him one of rock music\'s most distinctive and beloved performers.',
            ],
            [
                'first_name' => 'Taylor',
                'last_name' => 'Hawkins',
                'born' => '1972-02-17',
                'died' => '2022-03-25',
                'birth_place' => 'Fort Worth, Texas, USA',
                'death_place' => 'Bogotá, Colombia',
                'obituary' => 'Oliver Taylor Hawkins was an American musician best known as the drummer for the Foo Fighters. His energetic drumming style, infectious personality, and showmanship were integral to the band\'s sound and live performances. Before joining the Foo Fighters in 1997, Hawkins toured with Alanis Morissette. His charisma and musical talent extended to singing and songwriting, and his joyful presence behind the kit made him one of the most beloved rock drummers of his generation.',
            ],
            [
                'first_name' => 'Charlie',
                'last_name' => 'Watts',
                'born' => '1941-06-02',
                'died' => '2021-08-24',
                'birth_place' => 'London, England',
                'death_place' => 'London, England',
                'obituary' => 'Charles Robert Watts was an English musician best known as the drummer of the Rolling Stones from their formation in 1963 until his death. His jazz-influenced drumming style provided the Stones with their distinctive swing and groove. Unlike his flamboyant bandmates, Watts was known for his quiet elegance, sharp suits, and understated personality. He was inducted into the Rock and Roll Hall of Fame as a member of the Rolling Stones in 1989.',
            ],
            [
                'first_name' => 'Cicely',
                'last_name' => 'Tyson',
                'born' => '1924-12-19',
                'died' => '2021-01-28',
                'birth_place' => 'Harlem, New York City, USA',
                'death_place' => 'New York City, New York, USA',
                'obituary' => 'Cicely Tyson was an American actress and fashion model whose career spanned more than seven decades. She was known for her portrayal of strong African American women, choosing roles that advanced the images of Black people in film and television. Her performances in "Sounder," "The Autobiography of Miss Jane Pittman," and "The Help" earned numerous accolades including an honorary Academy Award. Tyson\'s commitment to dignity in representation blazed a trail for generations of Black artists.',
            ],
            [
                'first_name' => 'Larry',
                'last_name' => 'King',
                'born' => '1933-11-19',
                'died' => '2021-01-23',
                'birth_place' => 'Brooklyn, New York City, USA',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'Lawrence Harvey Zeiger, known as Larry King, was an American television and radio host whose career in broadcasting spanned over 60 years. As host of "Larry King Live" on CNN for 25 years, he conducted over 50,000 interviews with world leaders, celebrities, athletes, and newsmakers. King\'s signature suspenders, warm conversational style, and genuine curiosity made him one of the most recognized and respected broadcasters in American media history.',
            ],
            [
                'first_name' => 'Alex',
                'last_name' => 'Trebek',
                'born' => '1940-07-22',
                'died' => '2020-11-08',
                'birth_place' => 'Sudbury, Ontario, Canada',
                'death_place' => 'Los Angeles, California, USA',
                'obituary' => 'George Alexander Trebek was a Canadian-American television personality who hosted the syndicated game show "Jeopardy!" for 37 seasons from 1984 until his death. His calm demeanor, dry wit, and vast knowledge made him one of the most beloved figures in American television. When diagnosed with pancreatic cancer, Trebek spoke openly about his battle, raising awareness and inspiring millions. His legacy as a champion of knowledge and curiosity endures.',
            ],
            [
                'first_name' => 'Kirk',
                'last_name' => 'Douglas',
                'born' => '1916-12-09',
                'died' => '2020-02-05',
                'birth_place' => 'Amsterdam, New York, USA',
                'death_place' => 'Beverly Hills, California, USA',
                'obituary' => 'Kirk Douglas, born Issur Danielovitch, was an American actor and filmmaker who was one of the last surviving stars of Hollywood\'s Golden Age. Known for his intense performances and distinctive dimpled chin, Douglas starred in over 90 films including "Spartacus," "Paths of Glory," and "Lust for Life." He played a crucial role in ending the Hollywood blacklist by giving screenwriter Dalton Trumbo credit for "Spartacus." Douglas received an Honorary Academy Award for 50 years as a creative and moral force in cinema.',
            ],
            [
                'first_name' => 'Sean',
                'last_name' => 'Connery',
                'born' => '1930-08-25',
                'died' => '2020-10-31',
                'birth_place' => 'Edinburgh, Scotland',
                'death_place' => 'Nassau, Bahamas',
                'obituary' => 'Sir Thomas Sean Connery was a Scottish actor who was the first to portray secret agent James Bond on film, appearing in seven 007 films. His commanding screen presence, distinctive voice, and effortless charisma made him one of the most iconic actors in cinema history. Beyond Bond, Connery delivered acclaimed performances in "The Untouchables" (winning the Academy Award for Best Supporting Actor), "Indiana Jones and the Last Crusade," and "The Hunt for Red October."',
            ],
        ];
    }

    /**
     * @return list<string>
     */
    private function getTributeMessages(): array
    {
        return [
            'Your legacy will never be forgotten. Thank you for inspiring so many of us.',
            'A true legend. The world was better because you were in it.',
            'Rest in peace. Your work touched my life in ways I can never fully express.',
            'Gone too soon, but your impact will last forever.',
            'Thank you for the memories. You brought so much joy to the world.',
            'An incredible talent and an even more incredible human being.',
            'You changed the world for the better. We are forever grateful.',
            'Your spirit lives on in every life you touched.',
            'A shining light that will never be dimmed. Rest in eternal peace.',
            'The world lost a true icon, but your legacy is immortal.',
            'I grew up admiring you. Thank you for everything you gave us.',
            'Forever in our hearts. Your contributions will echo through the ages.',
            'A pioneer, a visionary, and an inspiration. Rest well.',
            'Your courage and dedication inspired millions around the world.',
            'No words can capture what you meant to so many people.',
            'You proved that one person can truly change the world.',
            'Missing you today and every day. Your light shines on.',
            'Thank you for showing us what greatness looks like.',
            'An extraordinary life, lived with passion and purpose.',
            'You made the world a more beautiful, meaningful place.',
        ];
    }
}
